# Generated by Django 5.1.2 on 2025-12-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ai_clean_title',
            field=models.CharField(blank=True, help_text='AI-generated polished title', max_length=200),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_coach_actions',
            field=models.JSONField(blank=True, default=list, help_text='Recommended AI Coach actions for this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_full_description',
            field=models.TextField(blank=True, help_text='AI-generated full description for student page'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_outcomes',
            field=models.JSONField(blank=True, default=list, help_text='List of outcomes this lesson will produce'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_short_summary',
            field=models.TextField(blank=True, help_text='AI-generated short summary for lesson list'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rough_notes',
            field=models.TextField(blank=True, help_text='Optional notes or outline for AI'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vimeo_duration_seconds',
            field=models.IntegerField(default=0, help_text='Duration in seconds from Vimeo'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='Vimeo video ID extracted from URL', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vimeo_thumbnail',
            field=models.URLField(blank=True, help_text='Vimeo thumbnail URL'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='vimeo_url',
            field=models.URLField(blank=True, help_text='Full Vimeo URL (e.g., https://vimeo.com/123456789)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='working_title',
            field=models.CharField(blank=True, help_text='Rough title before AI generation', max_length=200),
        ),
    ]
