# Generated by Django 5.1.2 on 2025-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_lesson_ai_clean_title_lesson_ai_coach_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='google_drive_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID', max_length=200),
        ),
        migrations.AddField(
            model_name='lesson',
            name='google_drive_url',
            field=models.URLField(blank=True, help_text='Google Drive video embed URL'),
        ),
    ]
