# Generated by Django 5.1.2 on 2025-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_lesson_google_drive_id_lesson_google_drive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transcription',
            field=models.TextField(blank=True, help_text='Auto-generated transcription from video'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcription_error',
            field=models.TextField(blank=True, help_text='Error message if transcription fails'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='transcription_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
