# Generated by Django 5.1.2 on 2025-12-12 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_lesson_transcription_lesson_transcription_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-last_accessed']},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_watched_timestamp',
            field=models.FloatField(default=0.0, help_text='Last timestamp in seconds where video was watched'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='video_completion_threshold',
            field=models.FloatField(default=90.0, help_text='Required watch percentage to complete (default 90%)'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='video_watch_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage of video watched (0-100)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='progress_percentage',
            field=models.IntegerField(default=0, help_text='Overall lesson progress percentage'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('passing_score', models.IntegerField(default=70, help_text='Minimum score percentage to pass')),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum number of attempts allowed (0 = unlimited)')),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Time limit in minutes (null = no limit)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='myApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, help_text='Score percentage (0-100)', null=True)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict, help_text="Student's answers")),
                ('is_final', models.BooleanField(default=False, help_text='Whether this is the final/current attempt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='myApp.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_eligible', 'Not Eligible'), ('eligible', 'Eligible'), ('passed', 'Passed - Certified'), ('failed', 'Failed - Retry Allowed')], default='not_eligible', max_length=20)),
                ('accredible_certificate_id', models.CharField(blank=True, help_text='Accredible certificate ID', max_length=200)),
                ('accredible_certificate_url', models.URLField(blank=True, help_text='Link to Accredible certificate')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='myApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
                ('passing_exam_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='myApp.examattempt')),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
