# Generated by Django 5.1.2 on 2025-12-16 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_lessonquiz_lessonquizattempt_lessonquizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='access_duration_days',
            field=models.IntegerField(blank=True, help_text="Fixed duration in days (if access_duration_type='fixed_days')", null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='access_duration_type',
            field=models.CharField(choices=[('lifetime', 'Lifetime Access'), ('fixed_days', 'Fixed Duration (days)'), ('until_date', 'Access Until Date'), ('drip', 'Drip Schedule')], default='lifetime', help_text='Access duration rule', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='access_until_date',
            field=models.DateTimeField(blank=True, help_text="Access expires on this date (if access_duration_type='until_date')", null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_method',
            field=models.CharField(choices=[('open', 'Open Enrollment (free/lead magnet)'), ('purchase', 'Purchase Required'), ('invite_only', 'Invite/Assigned Only'), ('cohort_only', 'Cohort Only'), ('subscription_only', 'Subscription Only')], default='open', help_text='How students get access', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses that must be completed first', related_name='unlocks_courses', to='myApp.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='required_quiz_score',
            field=models.IntegerField(blank=True, help_text='Required quiz score to unlock (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public (visible to anyone)'), ('members_only', 'Members Only (visible to logged-in users)'), ('hidden', 'Hidden (not in catalog, direct link only)'), ('private', 'Private (manual assignment only)')], default='public', help_text='Who can see this course exists', max_length=20),
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('bundle_type', models.CharField(choices=[('fixed', 'Fixed Bundle (curated set)'), ('pick_your_own', 'Pick Your Own (choose N courses)'), ('tiered', 'Tiered (Bronze/Silver/Gold)')], default='fixed', max_length=20)),
                ('max_course_selections', models.IntegerField(blank=True, help_text='For pick-your-own bundles', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='bundles', to='myApp.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BundlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_id', models.CharField(blank=True, help_text='External purchase/order ID', max_length=200)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myApp.bundle')),
                ('selected_courses', models.ManyToManyField(blank=True, help_text='For pick-your-own bundles', to='myApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True, help_text='Must complete to unlock next')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.course')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.learningpath')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('learning_path', 'course')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='courses',
            field=models.ManyToManyField(related_name='learning_paths', through='myApp.LearningPathCourse', to='myApp.course'),
        ),
        migrations.CreateModel(
            name='CohortMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('remove_access_on_leave', models.BooleanField(default=True, help_text='If True, removing from cohort revokes access. If False, access persists.')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='myApp.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('cohort', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('purchase', 'Purchase'), ('manual', 'Manual (Admin-granted)'), ('cohort', 'Cohort/Group'), ('subscription', 'Subscription/Membership'), ('bundle', 'Bundle Purchase')], max_length=20)),
                ('status', models.CharField(choices=[('unlocked', 'Unlocked (Active)'), ('locked', 'Locked'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('pending', 'Pending')], default='unlocked', max_length=20)),
                ('purchase_id', models.CharField(blank=True, help_text='External purchase ID', max_length=200)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Support notes, audit trail')),
                ('bundle_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to='myApp.bundlepurchase')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to='myApp.cohort')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='myApp.course')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who granted access (for manual access)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='Admin who revoked access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'course', 'status'], name='myApp_cours_user_id_9e9df5_idx'), models.Index(fields=['status', 'expires_at'], name='myApp_cours_status_1767f9_idx')],
            },
        ),
    ]
