# Generated by Django 5.1.2 on 2025-12-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_cohort_learningpath_course_access_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquiz',
            name='is_required',
            field=models.BooleanField(default=True, help_text='If true, quiz must be passed to complete the lesson.'),
        ),
    ]
