# Generated by Django 5.1.2 on 2025-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_alter_lessonquiz_is_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseaccess',
            name='purchase_id',
            field=models.CharField(blank=True, help_text='External purchase ID', max_length=200, null=True),
        ),
    ]








