# Generated by Django 5.1.2 on 2025-01-22 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_favoritecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Editor.js content blocks for lesson content'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]

