# Generated by Django 4.2.29 on 2026-04-22 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0017_courseresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_sop_program',
            field=models.BooleanField(default=False, help_text='If true, this course is treated as an SOP training program'),
        ),
        migrations.AddField(
            model_name='course',
            name='refresh_interval_days',
            field=models.IntegerField(default=90, help_text='Days before SOP refresh reminder is due'),
        ),
        migrations.AddField(
            model_name='course',
            name='sop_full_document',
            field=models.TextField(blank=True, help_text='AI-generated full SOP document'),
        ),
        migrations.AddField(
            model_name='course',
            name='sop_guidelines',
            field=models.TextField(blank=True, help_text='Internal SOP generation guidelines provided by admins'),
        ),
        migrations.AddField(
            model_name='course',
            name='sop_video_scripts',
            field=models.JSONField(blank=True, default=list, help_text='Generated video script blocks for SOP lessons'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_required_for_completion',
            field=models.BooleanField(default=True, help_text='If true, passing this exam is required for SOP completion'),
        ),
        migrations.CreateModel(
            name='TrainingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('assignment', 'Assignment'), ('incomplete', 'Incomplete Training'), ('exam_due', 'Exam Due'), ('refresh', 'Periodic Refresh')], max_length=20)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_reminders', to='myApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='myApp_train_status_4a1d07_idx'), models.Index(fields=['user', 'course', 'reminder_type'], name='myApp_train_user_id_0616d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('total_trainings_taken', models.IntegerField(default=0)),
                ('completed_trainings', models.IntegerField(default=0)),
                ('summary_text', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_summaries', to='myApp.course')),
                ('exam_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_summary', to='myApp.examattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('user', 'course', 'exam_attempt')},
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(default=django.utils.timezone.now)),
                ('productivity_score', models.FloatField(default=0, help_text='0-100')),
                ('quality_score', models.FloatField(default=0, help_text='0-100')),
                ('compliance_score', models.FloatField(default=0, help_text='0-100')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='myApp.course')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_performance_metrics', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-metric_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'course', 'metric_date'], name='myApp_emplo_user_id_b4ab60_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider', models.CharField(default='resend', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='myApp.course')),
                ('related_exam_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='myApp.examattempt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification_type', 'created_at'], name='myApp_email_notific_756e83_idx'), models.Index(fields=['recipient_email', 'status'], name='myApp_email_recipie_eb3fcb_idx')],
            },
        ),
    ]
